# Image nginx/nodejs: 
FROM nginx 

RUN apt-get update \ 
&& apt-get -y install vim \
&& apt-get -y install curl

RUN curl -sL https://deb.nodesource.com/setup_12.x | bash - \
&& apt-get install -y nodejs

RUN mkdir -p /var2/wwwd/images

RUN useradd docker

RUN chown -R docker:staff /var2

